// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BqKgm9uGRG8W5R8n1dtmSPp8bCiC5kg',
    appId: '1:261194911632:web:90f85d5610f0386225ed15',
    messagingSenderId: '261194911632',
    projectId: 'mental-math-trainer-app',
    authDomain: 'mental-math-trainer-app.firebaseapp.com',
    storageBucket: 'mental-math-trainer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe0Ucl3yW7oR6dLrFoVs5VRyNkbXVcZqY',
    appId: '1:261194911632:android:708d50fe725df19e25ed15',
    messagingSenderId: '261194911632',
    projectId: 'mental-math-trainer-app',
    storageBucket: 'mental-math-trainer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJSshnJp4vR3_39PuxNahd7StX9OJG-l4',
    appId: '1:261194911632:ios:8d59da8ca9892d8125ed15',
    messagingSenderId: '261194911632',
    projectId: 'mental-math-trainer-app',
    storageBucket: 'mental-math-trainer-app.firebasestorage.app',
    androidClientId:
        '261194911632-78g5ks718c4qq13iplr12e14t7ondfm7.apps.googleusercontent.com',
    iosClientId:
        '261194911632-g05gprs2e58jltsfemlo1kopms39v4mr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalMathTrainerApp',
  );
}
